# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hybrid Liberal Arts Network
tagline:          ‘High-Touch Learning for the 21st Century’
description:      A Teagle Project of the Midwest Hybrid Learning Consortium
url:              hybrid-liberal-arts.github.io
baseurl:          /

author:
  name:           ‘Barry Bandstra’
  url:            http://barrybandstra.com

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/hybrid-liberal-arts/hybrid-liberal-arts.github.io.git
