# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hybrid Liberal Arts Network
tagline:          ‘High-Touch Learning for the 21st Century’
description:      ’A Teagle Project of the Midwest Hybrid Liberal Arts Consortium’
url:              http://hybridliberalarts.org
baseurl:          /

author:
  name:           ‘Barry Bandstra’
  url:            http://bandstra@hope.edu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://hybrid-liberal-arts/hybrid-liberal-arts.github.io
