# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hybrid Liberal Arts Network
tagline:          ‘High-Touch Learning for the 21st Century’
description:      A Teagle Project of the Midwest Hybrid Learning Consortium
url:              http://hybrid-liberal-arts.github.io
baseurl:          /

author:
  name:           ‘Barry Bandstra’
  url:            http://barrybandstra.com

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://hybrid-liberal-arts.github.io
